api_task:
    pattern:  /
    defaults: { _controller: "JrowlandsnzTodoApiBundle:Task:indexApi", _format: ~ }
    methods:  GET
    
api_task_show:
    pattern:  /{id}
    defaults: { _controller: "JrowlandsnzTodoApiBundle:Task:showApi", _format: ~ }
    methods:  GET

