jrowlandsnz_todo_api_task:
    resource: "@JrowlandsnzTodoApiBundle/Resources/config/routing/task.yml"
    prefix:   /admin/task

jrowlandsnz_todo_api_project:
    resource: "@JrowlandsnzTodoApiBundle/Resources/config/routing/project.yml"
    prefix:   /admin/project

jrowlandsnz_todo_api_homepage:
    path:     /
    defaults: { _controller: JrowlandsnzTodoApiBundle:Default:index }

